@startuml
title Class Diagram - Line Types 01
note "Legend: The UML2 diagram demonstrates various line styles, \nsuch as solid, dashed, hollow diamonds, and filled \ndiamonds, to signify different types of relationships \nbetween Classes in a system model." as n1

package "Group1"{
  Lesson_Plan <|.. Lesson: implements a
  Car <|-- Ford: is a kind of
}


package "Group2"{
  House *-- Rooms: composed of
  Libarry o-- book: made up of
}

package "Group3"{
Meal .. Ingredients: dependent on
Man ..> Medication: dependent on
}

package "Group4"{
  Doctor  -- Patient: has a
  Thermometer --> Temperature: has a
}


/'Diagram Layout '/
Lesson -[hidden]-> Meal 
Rooms -[hidden]-> Doctor

@enduml